[feature-squad] fix: adjusts in endpoints and tests
angelovicentefilho/daily-manager pull request #3
Opened 2023-12-12 12:30 UTC by filipecsoares

2023-12-12 13:04 UTC, angelovicentefilho requested changes
De inicio via apenas essas modificações não quis colocar os Optional pq tu ja falou que vai alterar

2023-12-12 13:04 UTC, angelovicentefilho commented on src/main/java/br/com/jtech/services/daily/manager/adapters/input/controllers/squad/FindSquadByIdController.java
>  package br.com.jtech.services.daily.manager.adapters.input.controllers.squad;
Faltou fazer os testes de: Squad.java, SquadDocument.java, SquadRepository.java

2023-12-13 09:27 UTC, filipecsoares commented on src/test/java/br/com/jtech/services/daily/manager/application/core/usecases/squad/FindSquadByIdUseCaseTest.java
> +        assertThrows(IllegalArgumentException.class, () -> findSquadByIdUseCase.findById(invalidSquadId));
Coloquei lá, valeu!

2023-12-13 09:28 UTC, filipecsoares commented on src/test/java/br/com/jtech/services/daily/manager/application/core/usecases/squad/FindSquadByIdUseCaseTest.java
> +    public void testFindByIdWhenInvalidSquadIdThenThrowException() {
Criado o teste do not found

2023-12-13 09:29 UTC, filipecsoares commented on src/test/java/br/com/jtech/services/daily/manager/application/core/usecases/squad/FindSquadByIdUseCaseTest.java
> +public class FindSquadByIdUseCaseTest {
Removi o "public" das classes de testes.

2023-12-13 09:29 UTC, filipecsoares commented on src/main/java/br/com/jtech/services/daily/manager/adapters/input/controllers/squad/FindSquadByIdController.java
>  package br.com.jtech.services.daily.manager.adapters.input.controllers.squad;
Criado os testes

2023-12-13 23:18 UTC, merged